### ISSUE TITLE
Change library for generating QR Code

### ISSUE THREAD

**Issue by mint73** [suiranfes/shop.suiranfes.blue#54]
The last update of QRCoderNetCore is 2019 (five years ago). I think it is better to change it to [QRCoder](https://github.com/codebude/QRCoder).

**Comment by mint73** [comment]
or ZXing

**Comment by yogendrasgautam** [comment]
@mint73 Please let me know if I can take this issue?

**Comment by mint73** [comment]
@yogendrasgautam Yes, of course.
Thanks for your interest in contributing!

<details>
<summary>Description of this issue</summary>

We are currently using [QRCoderNetCore](https://www.nuget.org/packages/QRCoderNetCore/) as a library for creating QR codes. However, this has not been updated since 2019 and we would like to switch to the forked original [QRCoder](https://github.com/codebude/QRCoder/pkgs/nuget/QRCoder).

The changes are as follows.
```diff .xml
<!-- suiran.csproj -->
-     <PackageReference Include="QRCoderNetCore" Version="1.0.0" />
+     <PackageReference Include="QRCoder" Version="1.5.1" />
```

</details>
